keys:
  - &pastmaster age13xd7zpayk2dc2cpdzamx5wq35qyhp4s64lfq8utms8t74unt4u9s5skswd
  - &lab age1d9224u2wfaxwdvr3m88vkalznetgcuzruay95cacwztmaatqxdmsfgqgqx
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *pastmaster
      - *lab
